version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:3.0.2-hadoop3.2
    environment:
      INIT_DAEMON_STEP: setup_spark
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_HOST: postgres_container
      SPARK_HOME: '/spark'
    volumes:
      - ./output:/app
      - ./input:/input
    ports:
      - "7077:7077"
      - "4040:4040"
    depends_on:
      - postgres